plugins { id 'com.android.application' }

android {
    namespace 'xyz.app0773312'
    compileSdk 35

    defaultConfig {
        applicationId 'xyz.app0773312'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
